### ISSUE TITLE
Create a registration page with input fields for name, email, password, and confirm password

### ISSUE THREAD

**Issue by wahyusa** [wahyusa/react-consume-api#3]
## Goal

To create a registration page that allows users to sign up for the app.

## To-do list:

- [x] Create a new pages called `register.jsx`.
- [x] Add input fields for name, email, password, and confirm password.
- [x] Add validation to ensure that all fields are filled out correctly.
- [x] Add a submit button to the form.
- [x] Handle the form submission by sending a POST request to the RESTful API with the user’s information.
- [x] Display an error message if the registration fails but this is already handled by the API libs.
