### ISSUE TITLE
Create a login page with input fields for email and password

### ISSUE THREAD

**Issue by wahyusa** [wahyusa/react-consume-api#5]
## Goal

To create a login page that allows users to log in to the app.

## To-do list:

- [x] Create a new page called `login.jsx`.
- [x] Add input fields for email and password.
- [x] Add validation to ensure that both fields are filled out correctly [done by `api.js`].
- [x] Add a submit button to the form.
- [x] Handle the form submission by sending a POST request to the RESTful API with the user’s email and password.
- [x] Store the access token in local storage if the login is successful.
- [x] Display an error message if the login fails. [done by `api.js`].
