### ISSUE TITLE
Implement authentication and authorization using access token and local storage

### ISSUE THREAD

**Issue by wahyusa** [wahyusa/react-consume-api#7]
## Goal

To implement authentication and authorization using access token and local storage.

## To-do list:

- [x] Create a new context called `AuthContext.jsx`.
- [x] Check if the access token is stored in local storage.
- [x] If the access token is not stored in local storage, redirect the user to the login page.
- [x] If the access token is stored in local storage, send a GET request to the RESTful API to get the user’s information.
- [x] Store the user’s information in state.
- [x] Pass the user’s information down to child components as props.
- [x] Add authorization to the RESTful API by including the access token in the request headers.
- [x] Add a logout button that removes the access token from local storage and redirects the user to the login page.
